version: '3.8'
services:
    db:
        image: postgres
        volumes:
            - ./data/db:/var/lib/postgresql/data
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: main
        ports:
            - "5434:5432"         
    web:
        build: .
        command: 'python main.py'
        volumes:
            - .:/code
        ports:
            - "8000:8080"
        depends_on:
            - db
